### ISSUE TITLE
The VS project generated from cmake doesn't compile, seems not tested on Windows & Visual Studio

### ISSUE THREAD

**Issue by zhangxaochen** [lumark/PWP3D#3]
Seems the cmake version is for linux and not tested on Windows with VS.
I'm not quite familiar with writing good cmake, so I list several errors below when building the proj on Windows with vs2013 (generated by cmake):

1. _ITERATOR_DEBUG_LEVEL //LNK2038
FIX: comment this line: "set(CUDA_PROPAGATE_HOST_FLAGS off)"

2. error D8021: 无效的数值参数“/Wextra”    E:\Github\PWP3D\_build.vc12\Application\cl
FIX: remove the FLAG: -Wextra

3. pwp3d.lib is not generated after build, only .dll created. I have to change the output type from dll to lib in the project property page, but how can I fix it in CMakeLists.txt? 
I see the "if(MSVC)" part in cmakelists.txt, and also see a "pwp3d_export.h" file, but now sure how it works ;(

**Comment by lumark** [comment]
Hi Zhang,

I believe the VS version of the code can be downloaded from the author's website:

http://www.robots.ox.ac.uk/~victor/code.html

Best,
Lu

**Comment by zhangxaochen** [comment]
@lumark didn't see that page, thx!
